### ISSUE TITLE
[Q&A] about the provider or source

### ISSUE THREAD

**Issue by bachig26** [akionii/Miruro#17]
I just found your project and want to know if this uses the site scraping or torrent.

**Comment by akionii** [comment]
Yes, it indeed does use site scraping from Gogoanime and AniList, and as @Jeydin21 said the API isn't fully working for now. I'm terribly sorry for the very late response.

**Comment by akionii** [comment]
For now, I have been pretty busy and as it is one of my first backend projects this makes it hard for me to fix it, for now. I am still learning and I promise you, the moment I find a solution, I will be on it.

**Comment by gaminglnk** [comment]
You may checkout the consumet.ts library or consumet API in case of reference or usage.

**Comment by akionii** [comment]
thanks for the advice!

**Comment by gaminglnk** [comment]
How did you made the logo for this project ?
