### ISSUE TITLE
site keeps buffering

### ISSUE THREAD

**Issue by venkat2305** [akionii/Miruro#28]
**Describe the bug**
site keeps buffering

**To Reproduce**
1. open the website

**Expected behavior**
it should load anime posters

**Screenshots**
![image](https://user-images.githubusercontent.com/55329452/212825283-18889063-c0b6-45a7-839b-80d9df44a0db.png)

**Desktop (please complete the following information):**
 - WINDOWS 10
 -  - Browser [e.g. chrome, safari]

**Smartphone (please complete the following information):**
 - MICROSOFT EDGE

**Additional context**

**Comment by akionii** [comment]
Sorry for the late response, I'm sorry to tell you that that website in particular is just a preview.

**Comment by akionii** [comment]
It hasn't officially been uploaded.

**Comment by venkat2305** [comment]
I am watching the releases. Can you update the release when the full site live? Or update it here

**Comment by akionii** [comment]
For now the site still has many bugs and unresolved problems, mainly due to the backend... until these are solved the site will remain un-uploaded.
